# A docker compose file to run a blog server
#
# We need to make sure the db.sqlite3 database is stored on the host machine
# to maintain the data across rebuilds.

version: "3"

services:
  web:
    container_name: blog_web
    build: .
    env_file: .env
    volumes:
      - /srv/data/blog/:/data/
    ports:
      - "${PORT}:${PORT}"
    command: >
      gunicorn blog.asgi:application --workers 2 --max-requests 256
      --timeout 30 --bind :${PORT} --worker-class uvicorn.workers.UvicornWorker
      --log-file -
    restart: unless-stopped
  worker:
    container_name: blog_worker
    build: .
    env_file: .env
    volumes:
      - /srv/data/blog/:/data/
    command: >
      python3 manage.py scheduler
    restart: unless-stopped
