# A docker compose file to run a blog server
#
# We need to make sure the db.sqlite3 database is stored on the host machine
# to maintain the data across rebuilds.

version: "3"

services:
  web:
    container_name: blog
    build: .
    env_file: .env
    volumes:
      - /srv/data/blog/:/data/
    ports:
      - "${PORT}:${PORT}"
    command: yarn start:production
    restart: always
