# Generated by Django 4.0.5 on 2022-06-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_blogindexpage_body_alter_blogpostpage_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostpage',
            options={'ordering': ['-last_published_at'], 'verbose_name': 'Blog Page', 'verbose_name_plural': 'Blog Pages'},
        ),
    ]
