# Generated by Django 4.0.5 on 2022-06-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_command', models.CharField(choices=[('publish_scheduled_pages', 'Publish scheduled pages (recommended every hour)'), ('clearsessions', 'Clear sessions (recommended every day)')], max_length=255, unique=True)),
                ('run_interval', models.IntegerField(choices=[(300, 'Every 5 minutes'), (900, 'Every 15 minutes'), (1800, 'Every 30 minutes'), (3600, 'Every hour'), (86400, 'Every day')])),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
